### ISSUE TITLE
Need instructions

### ISSUE THREAD

**Issue by AviPairupuni** [psy0rz/stuff#1]
Hi Edwin, 

This looks promising. Could you please share more details and instructions on how to use these scripts. This would need a set of example on what to add and where. also would need an example of ignore instruction. 

Thank you, 
Avi

**Comment by psy0rz** [comment]
This is just a bunch of random scripts and stuff that i dont plan on documenting.

If you have a question about a specific script feel free to ask.

I also offer commercial support and customization for businesses.

Edwin
